name: Deploy Node App

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
            - name: Build Docker Image
              run: docker build -t akara840/mern-app-frontend --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}' .
            - name: Publish Image to docker hub
              run: docker push akara840/mern-app-frontend:latest
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull Image from the docker hub
              run: docker pull akara840/mern-app-frontend:latest
            - name: Delete old container
              run: docker rm -f mern-app-frontend-container
            - name: Run Docker container
              run: docker run -d -p 3000:80 --name mern-app-frontend-container akara840/mern-app-frontend